### ISSUE TITLE
Ignore class option for Error Tracking

### ISSUE THREAD

**Issue by ryush00** [DataDog/dd-trace-rb#3068]
**Is your feature request related to a problem? Please describe.**

While there are some errors that can be ignored to a certain extent, such as 404 errors, some 4XX errors should not be ignored.

Compared to other error tracking platforms, while other platforms allow you to ignore certain error classes, datadog ignores all 4XX errors by default. I think this is a bad practice.

If a client writes code incorrectly and gets an error like 422, and it's ignored because it's a 4XX error, it's going to make it harder to trace the error and more likely to cause a failure.

Or, like me, they might wonder why some errors aren't being tracked.

**Describe the goal of the feature**

It would be much better if we could set which classes to ignore via settings.

**Describe alternatives you've considered**

It was hardcoded, so we there's no alternative options.

**Additional context**
- #345

Below is the configuration documentation for another similar error tracking platform.
- https://docs.bugsnag.com/platforms/ruby/rails/configuration-options/#discard_classes
- https://docs.appsignal.com/guides/filter-data/ignore-errors.html
- https://docs.sentry.io/platforms/ruby/configuration/options/#:~:text=%27production%27%0Aend-,excluded_exceptions,-If%20you%20never

**Comment by benoittgt** [comment]
Hello @ryush00 🤗

Thanks for the detailed feature request. I started looking into that. Thanks for the links too. I love the very complet implementation made in sentry-ruby with various handling to get constant. Good work Stan 😏.

My todo list:
- [ ] By able to choose on Rails integration the list of class exceptions to ignore
- [ ] Provide by default a list of exceptions that match the actual behavior to avoid breaking change (?)
- [ ] Be able to override the list using constant
- [ ] Be able to use regex and not only string class definition
- [ ] Document how to exclude some class from default exceptions list

**Comment by benoittgt** [comment]
I [started](https://github.com/DataDog/dd-trace-rb/compare/master...benoittgt:dd-trace-rb:3068-excluded-exceptions-class) to work on this, but before going further. I think we need to hear what would be wanted from dd-trace-rb maintainers.

For example, we could ignore some exceptions on Rails part but still because it's a 5xx [it could be grabbed by in the rack tracing part](https://github.com/datadog/dd-trace-rb/blob/master/lib/datadog/tracing/contrib/rack/middlewares.rb#L237).

**Comment by dgmora** [comment]
This feels like a quite reasonable suggestion but there hasn't been an answer. Is there some other way that you can configure datadog to do that?

**Comment by Strech** [comment]
Hey folks 👋🏼 

I will take this question to the tracing team and will try to help with this one to be resolved.

**Comment by ryush00** [comment]
Thank you for tracing the issue.

I have made simple workaround monkeypatch. seems dirty but works

https://github.com/DataDog/dd-trace-rb/blame/2aa94dd0d42bd118c4a5bcb872b7fa9ecd52b090/lib/datadog/tracing/contrib/action_pack/utils.rb#L11

```ruby
module Datadog
  module Tracing
    module Contrib
      module ActionPack
        # Common utilities for ActionPack
        module Utils
          def self.exception_is_error?(exception)
            if defined?(::ActionDispatch::ExceptionWrapper)
              # Gets the equivalent status code for the exception (not all are 5XX)
              # You can add custom errors via `config.action_dispatch.rescue_responses`
              status = ::ActionDispatch::ExceptionWrapper.status_code_for_exception(exception.class.name)
              # Except 404, all exceptions are actually errors
              status.to_s != '404'
            else
              true
            end
          end
        end
      end
    end
  end
end
```

```diff
module Datadog
  module Tracing
    module Contrib
      module ActionPack
        # Common utilities for ActionPack
        module Utils
          def self.exception_is_error?(exception)
            if defined?(::ActionDispatch::ExceptionWrapper)
              # Gets the equivalent status code for the exception (not all are 5XX)
              # You can add custom errors via `config.action_dispatch.rescue_responses`
              status = ::ActionDispatch::ExceptionWrapper.status_code_for_exception(exception.class.name)
-              # Only 5XX exceptions are actually errors (e.g. don't flag 404s)
-              status.to_s.start_with?('5')
+              # Except 404, all exceptions are actually errors
+              status.to_s != '404'
            else
              true
            end
          end
        end
      end
    end
  end
end
```

**Comment by dgmora** [comment]
Hello, just by chance I saw that dd-trace python has something [exactly like that](https://github.com/search?q=repo%3ADataDog%2Fdd-trace-py%20DD_TRACE_HTTP_SERVER_ERROR_STATUSES&type=code) with `DD_TRACE_HTTP_SERVER_ERROR_STATUSES`.

Is this something that could be ported?

**Comment by Strech** [comment]
Summoning @DataDog/apm-idm-ruby for some help, seems reasonable adjustment.

**Comment by vpellan** [comment]
Hey ! We're going to take a look at this and hopefully add `DD_TRACE_HTTP_SERVER_ERROR_STATUSES` in the next few days. Thanks for your patience !

**Comment by vpellan** [comment]
Hello ! We've just merged a PR that adds `DD_TRACE_HTTP_SERVER_ERROR_STATUSES` configuration. It will be available in the next release ! Thanks !
